### ISSUE TITLE
Feature Request Gatsby 3

### ISSUE THREAD

**Issue by theapplegates** [bagseye/bonneville#22]
Any plans to update to Gatsby 3? I'm not a developer and ran into error messages Google could not help me with when I tried to follow Gatsby's migration guide from version 2 to 3. It's a great template. Very classic. 
Thanks 
Paul

**Comment by bagseye** [comment]
It is something I have been meaning to do but have not had an opportunity yet. I tested migrating on my personal site with took a bit of time but I shouldn't run into the same complications with this. I will update this ticket once it is migrated to v3

**Comment by theapplegates** [comment]
Thanks, I appreciate it. I'll work on it, maybe I can do it myself.

**Comment by theapplegates** [comment]
Thanks for upgrading it. It is working great.
