### ISSUE TITLE
Previous Page click does not work when a third page created.

### ISSUE THREAD

**Issue by burraksumer** [bagseye/bonneville#9]
After creating another blog post a new page in the Blog page is created. You can reach to that by simply clicking the "Next Page" button but when you reach the end(in my case the third page) it doesn't return to "/blog/2", it returns to just "/2".

**Comment by bagseye** [comment]
A solution for this has been pushed. Please see the following commit and make the change in `src/templates/blog-list-template.js` - 

[https://github.com/bagseye/bonneville/commit/5b6d14c7186499c3c96c29cd66bbb59da0f9ab3a](https://github.com/bagseye/bonneville/commit/5b6d14c7186499c3c96c29cd66bbb59da0f9ab3a)
